/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'IT000531' at '4/1/17 9:59 AM' with Gradle 2.14.1
 *
 * @author IT000531, @date 4/1/17 9:59 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
